on: [push, pull_request]
name: CI
jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Build and test with RSpec
      run: |
        bundle exec rails db:setup
        bundle exec rails assets:precompile
        bundle exec rspec
