on: [push, pull_request]
name: CI
jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Build and test with RSpec
      - uses: actions/checkout@v2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
